### ISSUE TITLE
use of laratablesQueryConditions

### ISSUE THREAD

**Issue by Rydeck** [freshbitsweb/laratables-demo#1]
In this demo (which I find very useful) you use all the possibilities of LaraTables except the method "laratablesQueryConditions".
I reproduced this demo because the project i'm working on is very similar. I need 3 queries (tables) on one page and I also use an accordeon to show them.
Each query however is a subset of a db table with differents where's. To alter my query (in stead of all data) I need to use laratablesQueryConditions, if I understood correctly.
However, the query that I place in this method will always be excecuted with that model and I need 3 different queries.
I would have liked to see an example of the use of this method in your demo but my question is in fact, is it even possible what I want?

**Comment by gauravmak** [comment]
It was not possible until now. A [pull-request](https://github.com/freshbitsweb/laratables/pull/11) by @cvsouth has added a feature and it is doable now.

Thanks.
